apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: todo-app
  namespace: todo-ns
spec:
  sourceRef:
    kind: GitRepository
    name: dwk-repo
  interval: 10m
  path: ./project
  prune: true
  validation: client