apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-secrets
  namespace: default
spec:
  interval: 10m
  path: "./project/manifests/secret.enc.yaml"
  prune: true
  sourceRef:
    kind: GitRepository
    name: dwk-repo
  decryption:
    provider: sops
    secretRef:
      name: sops-age